author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /adnotationes-et-meditationes-in-euangelia-test
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:b73fx/pages/emory:gt1z3/single-page/
image_size:
  page:
    height: 1000
    width: 688
  small-thumbnail:
    height: 100
    width: 68
  thumbnail:
    height: 300
    width: 206
permalink: pretty
publication_info:
  author: "Nadal, Ger\xF3nimo, 1507-1580."
  date: '2018'
  editors:
  - Sara Palmer
  tei_xml: tei.xml
  title: Adnotationes et meditationes in Euangelia quae in sacrosancto Missae sacrificio
    toto anno leguntur  cum eorundem Euangeliorum concordantia , an annotated digital
    edition
show_annotation_author: true
source_info:
  author: "Nadal, Ger\xF3nimo, 1507-1580."
  date: '1607'
  pdf_url: https://readux.ecds.emory.edu/books/emory:b73fx/pdf/#page=2
  title: 'Adnotationes et meditationes in Euangelia quae in sacrosancto Missae sacrificio
    toto anno leguntur  cum eorundem Euangeliorum concordantia '
  url: https://readux.ecds.emory.edu/books/emory:b73fx/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'Adnotationes et meditationes in Euangelia quae in sacrosancto Missae sacrificio
  toto anno leguntur  cum eorundem Euangeliorum concordantia '
url: https://sarepal.github.io
version: 0.7
